# Generated by Django 5.0.7 on 2024-07-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('transport', 'Transport'), ('maintenance', 'Maintenance'), ('fuel', 'Fuel'), ('other', 'Other')], max_length=100)),
                ('billing_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('canceled', 'Canceled')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
