# Generated by Django 5.0.7 on 2024-07-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='drivers/')),
                ('license_number', models.CharField(max_length=50)),
                ('license_image', models.ImageField(upload_to='licenses/')),
                ('identity_card_number', models.CharField(max_length=50)),
                ('identity_card_image', models.ImageField(upload_to='identity_cards/')),
                ('address', models.TextField()),
            ],
        ),
    ]
