# Generated by Django 5.0.7 on 2024-07-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervised_drivers', to='drivers.driver'),
        ),
    ]
