# Generated by Django 5.0.7 on 2024-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=50)),
                ('capacity', models.FloatField()),
                ('availability_status', models.BooleanField(default=True)),
            ],
        ),
    ]
