# Generated by Django 5.0.7 on 2024-07-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_last_maintenance_date_vehicle_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
