# Generated by Django 5.0.7 on 2024-07-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='latitude',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='longitude',
            field=models.CharField(max_length=10),
        ),
    ]
